language: ruby
rvm:
- 2.1.2
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- bundle exec rake db:test:prepare
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database wtbp_test;' -U postgres
addons:
  postgresql: '9.3'
test:
  adapter: postgresql
  database: wtbp_test
  username: postgres
deploy:
  provider: heroku
  api_key:
    secure: pEM1Z/UkaKk3P91LMLHVoDPM2e2l0K6d/af4uVYsKFRAhMQZgvPJbhxq/Tncr4nOX1N64iADe1YIPRklgIcXIStZWDZ1ICMnT/O1D8I05S/h99zc5rNjJJZbALeEMFCOzpABnt6ktb3EvLRqclaTNkAWODNh9oZ4wGl/2opDC8A=
  app: wtbp